#pragma once

#include <array>
#include <algorithm>
#include <bitset>
#include <ctime>
#include <cassert>
#include <cmath>
#include <exception>
#include <filesystem>
#include <functional>
#include <fstream>
#include <iostream>
#include <iomanip>
#include <iterator>
#include <map>
#include <memory>
#include <sstream>
#include <string>
#include <vector>
#include <unordered_map>
